# Generated by Django 2.0.3 on 2018-03-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20180308_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='source',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
