# Generated by Django 2.0.3 on 2018-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_historicalcontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('Online', 'Online Practice Contest (Virtual Contest)'), ('Onsite', 'Onsite Official Contest (ICPC / CCPC / GDCPC)')], default='Online', max_length=6),
        ),
        migrations.AddField(
            model_name='historicalcontest',
            name='contest_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontest',
            name='contest_type',
            field=models.CharField(choices=[('Online', 'Online Practice Contest (Virtual Contest)'), ('Onsite', 'Onsite Official Contest (ICPC / CCPC / GDCPC)')], default='Online', max_length=6),
        ),
    ]
