# Generated by Django 2.0.3 on 2018-03-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20180312_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalcontest',
            name='date',
            field=models.DateField(),
        ),
    ]
