# Generated by Django 2.0.3 on 2018-03-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.AddField(
            model_name='status',
            name='contributor',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
