# Generated by Django 2.0.3 on 2018-03-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('team_name', models.CharField(max_length=200)),
                ('team_member_1', models.CharField(max_length=200)),
                ('team_member_2', models.CharField(max_length=200)),
                ('team_member_3', models.CharField(max_length=200)),
            ],
        ),
    ]
