# Generated by Django 2.0.3 on 2018-03-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180311_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team_member_1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team_member_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team_member_3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
