# Generated by Django 2.0.3 on 2018-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180311_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
